name: Common

on:
  push:
    branches:
      - main
      - staging
      - develop
      - alpha
    paths:
      - 'common/**'
      - '.github/workflows/common.yml'
  pull_request:
    branches:
      - main
      - staging
      - develop
      - alpha
    paths:
      - 'common/**'
      - '.github/workflows/common.yml'

defaults:
  run:
    working-directory: 'common'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2022-12-10
        override: true
        components: rustfmt, clippy
    - name: Install Solc
      uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/ethereum/solidity/releases/download/v0.8.16/solc-static-linux'
        name: 'solc'
        version: '0.8.16'
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache cargo
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "common/libzkp/impl -> target"
    - name: Lint
      run: |
        rm -rf $HOME/.cache/golangci-lint 
        make lint
  goimports-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports
    - run: goimports -local scroll-tech/common/ -w .
    - run: go mod tidy
    # If there are any diffs from goimports or go mod tidy, fail.
    - name: Verify no changes from goimports and go mod tidy
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          exit 1
        fi
