name: Docker

on:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build coordinator docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/dockerfiles/coordinator.Dockerfile
        push: true
        tags: scrolltech/l2geth:${{github.ref_name}}
        # cache-from: type=gha,scope=${{ github.workflow }}
        # cache-to: type=gha,scope=${{ github.workflow }}
    - name: Build event_watcher docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/dockerfiles/event_watcher.Dockerfile
        push: true
        tags: scrolltech/l2geth:${{github.ref_name}}
        # cache-from: type=gha,scope=${{ github.workflow }}
        # cache-to: type=gha,scope=${{ github.workflow }}
    - name: Build gas_oracle docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/dockerfiles/gas_oracle.Dockerfile
        push: true
        tags: scrolltech/l2geth:${{github.ref_name}}
        # cache-from: type=gha,scope=${{ github.workflow }}
        # cache-to: type=gha,scope=${{ github.workflow }}
    - name: Build msg_relayer docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/dockerfiles/msg_relayer.Dockerfile
        push: true
        tags: scrolltech/l2geth:${{github.ref_name}}
        # cache-from: type=gha,scope=${{ github.workflow }}
        # cache-to: type=gha,scope=${{ github.workflow }}
    - name: Build rollup_relayer docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/dockerfiles/rollup_relayer.Dockerfile
        push: true
        tags: scrolltech/l2geth:${{github.ref_name}}
        # cache-from: type=gha,scope=${{ github.workflow }}
        # cache-to: type=gha,scope=${{ github.workflow }}
